# Generated by Django 6.0.6 on 2026-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_superuser',
            new_name='is_superuser',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(default='/media/avatars/default-avatar.png'),
        ),
    ]
