# Generated by Django 6.0.6 on 2026-06-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.TextField()),
            ],
            options={
                'db_table': 'audio_attachments',
            },
        ),
        migrations.CreateModel(
            name='Fileattachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('extension', models.CharField(max_length=15)),
                ('size', models.FloatField()),
                ('src', models.TextField()),
                ('content_type', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'file_attachment',
            },
        ),
    ]
