# Generated by Django 6.0.6 on 2026-06-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fileattachment',
            table='file_attachments',
        ),
    ]
